In [1]:
import os
import wandb
from dotenv import load_dotenv

load_dotenv()
# Read the WandB API key from the environment variable
api_key = os.getenv("WANDB_API_KEY")
if api_key:
    wandb.login(key=api_key)
else:
    print("WANDB_API_KEY not found in environment. Please set it to your WandB API key.")
wandb.require("core")


wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: beehappy2554 (beehappy2554-bosch-global) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING `wandb.require('core')` is redundant as it is now the default behavior.


In [2]:
# sweep_config = {
#     'program': 'train.py',
#     'method': 'random',  # Can be 'grid', 'random', or 'bayes'
#     'metric': {
#         'name': 'val_loss',  # The metric to optimize
#         'goal': 'minimize'  # The optimization goal of the metric
#     },
#     'parameters': {
#         'lr': {
#             'distribution': 'uniform',
#             'min': 1e-6,
#             'max': 1e-2
#         },
#         'num_epochs': {
#             'values': [10, 20, 30]
#         },
#         'batch_size': {
#             'values': [16, 32, 64]
#         },
#         'optimizer': {
#             'values': ['adam', 'sgd', 'adamw']
#         },
#         # You can add more hyperparameters as needed.
#     }
# }

import wandb
from utils.helper import load_config
config_path = "../config/sweep_model.yaml"

PROJECT = 'hutech_mushroom'
with open(config_path, 'r') as f:
    sweep_config = load_config(config_path)
print(sweep_config)
sweep_id = wandb.sweep(sweep_config, project=PROJECT)
print(f"Sweep ID: {sweep_id}")

/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


{'program': 'train.py', 'name': 'model_sweep', 'method': 'grid', 'metric': {'name': 'test_accuracy', 'goal': 'maximize'}, 'parameters': {'model': {'values': ['alexnet', 'convnext', 'densenet', 'efficientnet', 'mobilenet', 'resnet', 'vit', 'inception', 'negnet', 'resnext', 'shufflenet']}, 'dataset': {'value': 'hutech-dataset:latest'}, 'resize': {'values': [224]}, 'horizontal_flip': {'values': [0.5]}, 'vertical_flip': {'values': [0.5]}, 'random_rotation': {'values': [90]}, 'contrast': {'values': [0.2]}, 'saturation': {'values': [0.2]}, 'num_classes': {'value': 4}, 'lr': {'value': '1e-5'}, 'num_epochs': {'value': 30}, 'batch_size': {'value': 4}, 'optimizer': {'value': 'adam'}, 'scheduler': {'value': 'reduce_lr_on_plateau'}, 'es_patience': {'value': 10}, 'weight_decay': {'value': 0.0001}, 'momentum': {'value': 0.9}}, 'command': ['${env}', 'python', '${program}']}
Create sweep with ID: v1g5ljm5
Sweep URL: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/sweeps/v1g5ljm5
Sweep ID: v

- 2 ways to activate agent for sweeping:

In [ ]:
from train import trainer
print(f"Sweep ID: {sweep_id}")
wandb.agent(sweep_id)

Sweep ID: l64vt3el


wandb: Agent Starting Run: 1usdczqc with config:
wandb: 	batch_size: 4
wandb: 	brightness: 0
wandb: 	contrast: 0
wandb: 	dataset: hutech-dataset:latest
wandb: 	es_patience: 10
wandb: 	horizontal_flip: 0
wandb: 	hue: 0
wandb: 	lr: 1e-05
wandb: 	model: alexnet
wandb: 	momentum: 0.9
wandb: 	num_classes: 4
wandb: 	num_epochs: 30
wandb: 	optimizer: adam
wandb: 	random_rotation: 0
wandb: 	resize: 224
wandb: 	saturation: 0
wandb: 	scheduler: reduce_lr_on_plateau
wandb: 	vertical_flip: 0.5
wandb: 	weight_decay: 0.0001


args Namespace(model='alexnet', config=None, project='hutech_mushroom', dataset='hutech-dataset:latest')


wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: beehappy2554 (beehappy2554-bosch-global) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Ignoring project 'hutech_mushroom' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/wandb/run-20250329_133518-1usdczqc
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run serene-sweep-2
wandb: ⭐️ View project at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: 🧹 View sweep at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/sweeps/l64vt3el
wandb: 🚀 View run at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/1usdczqc


here config!!! None
HERE config! {'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 0, 'resize': 224, 'saturation': 0, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0.5, 'weight_decay': 0.0001}


wandb:   1205 of 1205 files downloaded.  


{'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 0, 'resize': 224, 'saturation': 0, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0.5, 'weight_decay': 0.0001}
Training model...
Device: cuda
Number of epochs: 30
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 1e-05
    maximize: False
    weight_decay: 0.0001
)
Criterion: CrossEntropyLoss()
Scheduler: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x7f08b0a8d8b0>
Batch size: 4
Early stopping: 10
Dataset: 720 training samples, 120 validation samples


  1%|          | 2/180 [00:00<00:10, 16.88it/s]

[Epoch 1/30] Train Loss: 1.1307 Val Loss: 0.8115 Train Acc: 0.5458 Val Acc: 0.6833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 2/30] Train Loss: 0.5602 Val Loss: 0.3730 Train Acc: 0.8069 Val Acc: 0.8917


  1%|          | 2/180 [00:00<00:10, 16.76it/s]

[Epoch 3/30] Train Loss: 0.2807 Val Loss: 0.1854 Train Acc: 0.9125 Val Acc: 0.9417


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 4/30] Train Loss: 0.2167 Val Loss: 0.1589 Train Acc: 0.9153 Val Acc: 0.9583


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 5/30] Train Loss: 0.1649 Val Loss: 0.0951 Train Acc: 0.9431 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 6/30] Train Loss: 0.1199 Val Loss: 0.0754 Train Acc: 0.9681 Val Acc: 0.9750


  1%|          | 2/180 [00:00<00:09, 18.10it/s]

[Epoch 7/30] Train Loss: 0.0908 Val Loss: 0.0970 Train Acc: 0.9681 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 8/30] Train Loss: 0.0735 Val Loss: 0.0574 Train Acc: 0.9792 Val Acc: 0.9750


  1%|          | 2/180 [00:00<00:10, 17.44it/s]

[Epoch 9/30] Train Loss: 0.0481 Val Loss: 0.0430 Train Acc: 0.9875 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 10/30] Train Loss: 0.0462 Val Loss: 0.0319 Train Acc: 0.9861 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 11/30] Train Loss: 0.0345 Val Loss: 0.0292 Train Acc: 0.9931 Val Acc: 1.0000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 12/30] Train Loss: 0.0446 Val Loss: 0.0716 Train Acc: 0.9861 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 13/30] Train Loss: 0.0224 Val Loss: 0.0592 Train Acc: 0.9958 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 14/30] Train Loss: 0.0441 Val Loss: 0.1279 Train Acc: 0.9819 Val Acc: 0.9500


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 15/30] Train Loss: 0.0313 Val Loss: 0.0585 Train Acc: 0.9903 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 16/30] Train Loss: 0.0183 Val Loss: 0.0520 Train Acc: 0.9944 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 17/30] Train Loss: 0.0122 Val Loss: 0.0188 Train Acc: 0.9972 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 18/30] Train Loss: 0.0091 Val Loss: 0.0227 Train Acc: 1.0000 Val Acc: 0.9917


  1%|          | 2/180 [00:00<00:10, 17.51it/s]

[Epoch 19/30] Train Loss: 0.0084 Val Loss: 0.0153 Train Acc: 0.9986 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 20/30] Train Loss: 0.0105 Val Loss: 0.0614 Train Acc: 0.9986 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 21/30] Train Loss: 0.0044 Val Loss: 0.0157 Train Acc: 1.0000 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 22/30] Train Loss: 0.0027 Val Loss: 0.0309 Train Acc: 1.0000 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 23/30] Train Loss: 0.0152 Val Loss: 0.1964 Train Acc: 0.9931 Val Acc: 0.9417


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 24/30] Train Loss: 0.0567 Val Loss: 0.0565 Train Acc: 0.9833 Val Acc: 0.9833


  1%|          | 2/180 [00:00<00:10, 17.46it/s]

[Epoch 25/30] Train Loss: 0.0073 Val Loss: 0.0361 Train Acc: 0.9986 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 26/30] Train Loss: 0.0040 Val Loss: 0.0160 Train Acc: 1.0000 Val Acc: 1.0000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 27/30] Train Loss: 0.0035 Val Loss: 0.0260 Train Acc: 1.0000 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 28/30] Train Loss: 0.0013 Val Loss: 0.0178 Train Acc: 1.0000 Val Acc: 1.0000


100%|██████████| 120/120 [00:00<00:00, 137.95it/s]


[Epoch 29/30] Train Loss: 0.0013 Val Loss: 0.0345 Train Acc: 1.0000 Val Acc: 0.9917
Early stopping triggered
Testing model...
Accuracy: 0.9861111111111112
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        90
           1       0.98      0.99      0.98        90
           2       0.98      1.00      0.99        90
           3       0.99      0.98      0.98        90

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360

Confusion Matrix:
 [[88  0  1  1]
 [ 0 89  1  0]
 [ 0  0 90  0]
 [ 0  2  0 88]]
Test time: 2.55 seconds
Test Accuracy: 0.9861
Model saved at ../models/alexnet-2025-03-29-13:35:28.pt


wandb: uploading artifact alexnet-model; uploading wandb-summary.json; uploading config.yaml
wandb: uploading artifact alexnet-model
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:  train_acc ▁▅▇▇▇████████████████████████
wandb: train_loss █▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:    val_acc ▁▆▇▇▇▇▇▇███▇▇▇█▇███▇██▇█▇████
wandb:   val_loss █▄▂▂▂▂▂▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:  train_acc 1
wandb: train_loss 0.00131
wandb:    val_acc 0.99167
wandb:   val_loss 0.03452
wandb: 
wandb: 🚀 View run serene-sweep-2 at: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/1usdczqc
wandb: ⭐️ View project at: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: Synced 5 W&B file(s), 1 media file(s), 4 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250329_133518-1usdczqc/logs
wandb: Agent Starting Run: 97cp8i4w with config:
wandb: 	batch_size: 4
wandb: 	bri

args Namespace(model='alexnet', config=None, project='hutech_mushroom', dataset='hutech-dataset:latest')


wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: beehappy2554 (beehappy2554-bosch-global) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Ignoring project 'hutech_mushroom' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/wandb/run-20250329_134147-97cp8i4w
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run revived-sweep-3
wandb: ⭐️ View project at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: 🧹 View sweep at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/sweeps/l64vt3el
wandb: 🚀 View run at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/97cp8i4w


here config!!! None
HERE config! {'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 0, 'resize': 224, 'saturation': 0.2, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0, 'weight_decay': 0.0001}


wandb:   1205 of 1205 files downloaded.  


{'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 0, 'resize': 224, 'saturation': 0.2, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0, 'weight_decay': 0.0001}
Training model...
Device: cuda
Number of epochs: 30
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 1e-05
    maximize: False
    weight_decay: 0.0001
)
Criterion: CrossEntropyLoss()
Scheduler: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x7fc056087850>
Batch size: 4
Early stopping: 10
Dataset: 720 training samples, 120 validation samples


  1%|          | 2/180 [00:00<00:09, 18.03it/s]

[Epoch 1/30] Train Loss: 0.9240 Val Loss: 0.5068 Train Acc: 0.6889 Val Acc: 0.8417


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 2/30] Train Loss: 0.3265 Val Loss: 0.2885 Train Acc: 0.9097 Val Acc: 0.8917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 3/30] Train Loss: 0.1786 Val Loss: 0.1708 Train Acc: 0.9444 Val Acc: 0.9167


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 4/30] Train Loss: 0.0961 Val Loss: 0.2965 Train Acc: 0.9722 Val Acc: 0.9000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 5/30] Train Loss: 0.0612 Val Loss: 0.0978 Train Acc: 0.9861 Val Acc: 0.9667


  1%|          | 2/180 [00:00<00:10, 16.89it/s]

[Epoch 6/30] Train Loss: 0.0476 Val Loss: 0.1151 Train Acc: 0.9861 Val Acc: 0.9583


  1%|          | 2/180 [00:00<00:10, 16.30it/s]

[Epoch 7/30] Train Loss: 0.0437 Val Loss: 0.1143 Train Acc: 0.9875 Val Acc: 0.9417


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 8/30] Train Loss: 0.0179 Val Loss: 0.1270 Train Acc: 0.9986 Val Acc: 0.9500


  1%|          | 2/180 [00:00<00:10, 16.64it/s]

[Epoch 9/30] Train Loss: 0.0197 Val Loss: 0.0928 Train Acc: 0.9917 Val Acc: 0.9667


  1%|          | 2/180 [00:00<00:10, 16.26it/s]

[Epoch 10/30] Train Loss: 0.0117 Val Loss: 0.0909 Train Acc: 0.9986 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 11/30] Train Loss: 0.0149 Val Loss: 0.1168 Train Acc: 0.9986 Val Acc: 0.9750


  1%|          | 2/180 [00:00<00:10, 16.97it/s]

[Epoch 12/30] Train Loss: 0.0037 Val Loss: 0.1233 Train Acc: 1.0000 Val Acc: 0.9583


  1%|          | 2/180 [00:00<00:10, 16.48it/s]

[Epoch 13/30] Train Loss: 0.0026 Val Loss: 0.0746 Train Acc: 1.0000 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 14/30] Train Loss: 0.0032 Val Loss: 0.0630 Train Acc: 1.0000 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 15/30] Train Loss: 0.0014 Val Loss: 0.0873 Train Acc: 1.0000 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 16/30] Train Loss: 0.0065 Val Loss: 0.0821 Train Acc: 0.9972 Val Acc: 0.9500


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 17/30] Train Loss: 0.0028 Val Loss: 0.0997 Train Acc: 1.0000 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 18/30] Train Loss: 0.0024 Val Loss: 0.1727 Train Acc: 1.0000 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 19/30] Train Loss: 0.0007 Val Loss: 0.1012 Train Acc: 1.0000 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 20/30] Train Loss: 0.0229 Val Loss: 0.1493 Train Acc: 0.9931 Val Acc: 0.9583


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 21/30] Train Loss: 0.0054 Val Loss: 0.0873 Train Acc: 0.9986 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 22/30] Train Loss: 0.0011 Val Loss: 0.0661 Train Acc: 1.0000 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 23/30] Train Loss: 0.0007 Val Loss: 0.0977 Train Acc: 1.0000 Val Acc: 0.9750


100%|██████████| 120/120 [00:00<00:00, 134.97it/s]


[Epoch 24/30] Train Loss: 0.0011 Val Loss: 0.1256 Train Acc: 1.0000 Val Acc: 0.9667
Early stopping triggered
Testing model...
Accuracy: 0.9861111111111112
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        90
           1       0.99      0.97      0.98        90
           2       0.99      1.00      0.99        90
           3       0.97      0.98      0.97        90

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360

Confusion Matrix:
 [[90  0  0  0]
 [ 0 87  0  3]
 [ 0  0 90  0]
 [ 0  1  1 88]]
Test time: 2.56 seconds
Test Accuracy: 0.9861
Model saved at ../models/alexnet-2025-03-29-13:41:56.pt


wandb: uploading artifact alexnet-model; uploading wandb-summary.json; uploading config.yaml
wandb: uploading artifact alexnet-model
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:  train_acc ▁▆▇▇████████████████████
wandb: train_loss █▃▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:    val_acc ▁▄▅▄█▇▆▇███▇███▇███▇████
wandb:   val_loss █▅▃▅▂▂▂▂▁▁▂▂▁▁▁▁▂▃▂▂▁▁▂▂
wandb: 
wandb: Run summary:
wandb:  train_acc 1
wandb: train_loss 0.00112
wandb:    val_acc 0.96667
wandb:   val_loss 0.12563
wandb: 
wandb: 🚀 View run revived-sweep-3 at: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/97cp8i4w
wandb: ⭐️ View project at: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: Synced 5 W&B file(s), 1 media file(s), 4 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250329_134147-97cp8i4w/logs
wandb: Agent Starting Run: jrgpvy9v with config:
wandb: 	batch_size: 4
wandb: 	brightness: 0
wandb: 	

args Namespace(model='alexnet', config=None, project='hutech_mushroom', dataset='hutech-dataset:latest')


wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: beehappy2554 (beehappy2554-bosch-global) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Ignoring project 'hutech_mushroom' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/wandb/run-20250329_134727-jrgpvy9v
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run dutiful-sweep-4
wandb: ⭐️ View project at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: 🧹 View sweep at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/sweeps/l64vt3el
wandb: 🚀 View run at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/jrgpvy9v


here config!!! None
HERE config! {'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 0, 'resize': 224, 'saturation': 0.2, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0.5, 'weight_decay': 0.0001}


wandb:   1205 of 1205 files downloaded.  


{'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 0, 'resize': 224, 'saturation': 0.2, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0.5, 'weight_decay': 0.0001}
Training model...
Device: cuda
Number of epochs: 30
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 1e-05
    maximize: False
    weight_decay: 0.0001
)
Criterion: CrossEntropyLoss()
Scheduler: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x7f33f7028a30>
Batch size: 4
Early stopping: 10
Dataset: 720 training samples, 120 validation samples


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 1/30] Train Loss: 1.0615 Val Loss: 0.6930 Train Acc: 0.5819 Val Acc: 0.8000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 2/30] Train Loss: 0.5099 Val Loss: 0.3977 Train Acc: 0.8333 Val Acc: 0.8750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 3/30] Train Loss: 0.2968 Val Loss: 0.1736 Train Acc: 0.8944 Val Acc: 0.9250


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 4/30] Train Loss: 0.1912 Val Loss: 0.1237 Train Acc: 0.9361 Val Acc: 0.9583


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 5/30] Train Loss: 0.1301 Val Loss: 0.1688 Train Acc: 0.9597 Val Acc: 0.9250


  1%|          | 2/180 [00:00<00:11, 16.11it/s]

[Epoch 6/30] Train Loss: 0.1208 Val Loss: 0.0638 Train Acc: 0.9569 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 7/30] Train Loss: 0.1007 Val Loss: 0.0977 Train Acc: 0.9694 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 8/30] Train Loss: 0.0582 Val Loss: 0.0384 Train Acc: 0.9833 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 9/30] Train Loss: 0.0441 Val Loss: 0.0470 Train Acc: 0.9903 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 10/30] Train Loss: 0.0610 Val Loss: 0.0420 Train Acc: 0.9792 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 11/30] Train Loss: 0.0402 Val Loss: 0.0603 Train Acc: 0.9917 Val Acc: 0.9667


  1%|          | 2/180 [00:00<00:10, 17.12it/s]

[Epoch 12/30] Train Loss: 0.0310 Val Loss: 0.0361 Train Acc: 0.9903 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 13/30] Train Loss: 0.0286 Val Loss: 0.0390 Train Acc: 0.9931 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 14/30] Train Loss: 0.0127 Val Loss: 0.0172 Train Acc: 1.0000 Val Acc: 1.0000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 15/30] Train Loss: 0.0230 Val Loss: 0.0742 Train Acc: 0.9917 Val Acc: 0.9667


  1%|          | 2/180 [00:00<00:10, 17.18it/s]

[Epoch 16/30] Train Loss: 0.0267 Val Loss: 0.0582 Train Acc: 0.9931 Val Acc: 0.9667


  1%|          | 2/180 [00:00<00:10, 16.74it/s]

[Epoch 17/30] Train Loss: 0.0201 Val Loss: 0.0679 Train Acc: 0.9944 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 18/30] Train Loss: 0.0210 Val Loss: 0.0367 Train Acc: 0.9944 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 19/30] Train Loss: 0.0172 Val Loss: 0.0238 Train Acc: 0.9944 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 20/30] Train Loss: 0.0135 Val Loss: 0.0359 Train Acc: 0.9986 Val Acc: 0.9833


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 21/30] Train Loss: 0.0149 Val Loss: 0.0275 Train Acc: 0.9958 Val Acc: 0.9917


  1%|          | 2/180 [00:00<00:10, 17.14it/s]

[Epoch 22/30] Train Loss: 0.0047 Val Loss: 0.0145 Train Acc: 1.0000 Val Acc: 1.0000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 23/30] Train Loss: 0.0107 Val Loss: 0.0233 Train Acc: 0.9986 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 24/30] Train Loss: 0.0248 Val Loss: 0.2523 Train Acc: 0.9917 Val Acc: 0.9333


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 25/30] Train Loss: 0.0236 Val Loss: 0.0162 Train Acc: 0.9931 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 26/30] Train Loss: 0.0185 Val Loss: 0.0139 Train Acc: 0.9958 Val Acc: 0.9917


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 27/30] Train Loss: 0.0031 Val Loss: 0.0148 Train Acc: 1.0000 Val Acc: 1.0000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 28/30] Train Loss: 0.0011 Val Loss: 0.0101 Train Acc: 1.0000 Val Acc: 1.0000


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 29/30] Train Loss: 0.0046 Val Loss: 0.0129 Train Acc: 0.9986 Val Acc: 1.0000


100%|██████████| 120/120 [00:00<00:00, 143.74it/s]


[Epoch 30/30] Train Loss: 0.0017 Val Loss: 0.0100 Train Acc: 1.0000 Val Acc: 1.0000
Testing model...
Accuracy: 0.9916666666666667
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        90
           1       0.99      0.98      0.98        90
           2       0.99      1.00      0.99        90
           3       0.99      0.99      0.99        90

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360

Confusion Matrix:
 [[90  0  0  0]
 [ 0 88  1  1]
 [ 0  0 90  0]
 [ 0  1  0 89]]
Test time: 2.43 seconds
Test Accuracy: 0.9917
Model saved at ../models/alexnet-2025-03-29-13:47:35.pt


wandb: uploading artifact alexnet-model; uploading wandb-summary.json; uploading config.yaml
wandb: uploading artifact alexnet-model
wandb: uploading data
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:  train_acc ▁▅▆▇▇▇▇███████████████████████
wandb: train_loss █▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:    val_acc ▁▄▅▇▅▇▇██▇▇███▇▇▇▇▇▇███▆██████
wandb:   val_loss █▅▃▂▃▂▂▁▁▁▂▁▁▁▂▁▂▁▁▁▁▁▁▃▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:  train_acc 1
wandb: train_loss 0.00165
wandb:    val_acc 1
wandb:   val_loss 0.00997
wandb: 
wandb: 🚀 View run dutiful-sweep-4 at: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/jrgpvy9v
wandb: ⭐️ View project at: https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: Synced 5 W&B file(s), 1 media file(s), 4 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250329_134727-jrgpvy9v/logs
wandb: Agent Starting Run: z160eumf with config:
wandb: 	batc

args Namespace(model='alexnet', config=None, project='hutech_mushroom', dataset='hutech-dataset:latest')


wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: beehappy2554 (beehappy2554-bosch-global) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Ignoring project 'hutech_mushroom' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/wandb/run-20250329_135424-z160eumf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run neat-sweep-5
wandb: ⭐️ View project at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom
wandb: 🧹 View sweep at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/sweeps/l64vt3el
wandb: 🚀 View run at https://wandb.ai/beehappy2554-bosch-global/hutech_mushroom/runs/z160eumf


here config!!! None
HERE config! {'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 90, 'resize': 224, 'saturation': 0, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0, 'weight_decay': 0.0001}


wandb:   1205 of 1205 files downloaded.  


{'batch_size': 4, 'brightness': 0, 'contrast': 0, 'dataset': 'hutech-dataset:latest', 'es_patience': 10, 'horizontal_flip': 0, 'hue': 0, 'lr': 1e-05, 'model': 'alexnet', 'momentum': 0.9, 'num_classes': 4, 'num_epochs': 30, 'optimizer': 'adam', 'random_rotation': 90, 'resize': 224, 'saturation': 0, 'scheduler': 'reduce_lr_on_plateau', 'vertical_flip': 0, 'weight_decay': 0.0001}
Training model...
Device: cuda
Number of epochs: 30
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 1e-05
    maximize: False
    weight_decay: 0.0001
)
Criterion: CrossEntropyLoss()
Scheduler: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x7f8bcbdf9d00>
Batch size: 4
Early stopping: 10
Dataset: 720 training samples, 120 validation samples


  1%|          | 2/180 [00:00<00:09, 18.48it/s]

[Epoch 1/30] Train Loss: 1.1617 Val Loss: 1.0231 Train Acc: 0.5028 Val Acc: 0.5667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 2/30] Train Loss: 0.5717 Val Loss: 0.5562 Train Acc: 0.8111 Val Acc: 0.7917


  1%|          | 2/180 [00:00<00:09, 17.90it/s]

[Epoch 3/30] Train Loss: 0.3402 Val Loss: 0.3669 Train Acc: 0.8708 Val Acc: 0.8750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 4/30] Train Loss: 0.2253 Val Loss: 0.2541 Train Acc: 0.9250 Val Acc: 0.9083


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 5/30] Train Loss: 0.1834 Val Loss: 0.1558 Train Acc: 0.9347 Val Acc: 0.9500


  1%|          | 2/180 [00:00<00:10, 17.00it/s]

[Epoch 6/30] Train Loss: 0.1565 Val Loss: 0.1898 Train Acc: 0.9486 Val Acc: 0.9167


  1%|          | 2/180 [00:00<00:10, 17.15it/s]

[Epoch 7/30] Train Loss: 0.1435 Val Loss: 0.1751 Train Acc: 0.9444 Val Acc: 0.9250


  1%|          | 2/180 [00:00<00:10, 16.87it/s]

[Epoch 8/30] Train Loss: 0.1130 Val Loss: 0.0898 Train Acc: 0.9611 Val Acc: 0.9667


  1%|          | 2/180 [00:00<00:10, 17.47it/s]

[Epoch 9/30] Train Loss: 0.0906 Val Loss: 0.1441 Train Acc: 0.9694 Val Acc: 0.9500


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 10/30] Train Loss: 0.0915 Val Loss: 0.0807 Train Acc: 0.9681 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 11/30] Train Loss: 0.0806 Val Loss: 0.0810 Train Acc: 0.9694 Val Acc: 0.9750


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 12/30] Train Loss: 0.0600 Val Loss: 0.0845 Train Acc: 0.9819 Val Acc: 0.9583


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 13/30] Train Loss: 0.0693 Val Loss: 0.0772 Train Acc: 0.9736 Val Acc: 0.9667


  0%|          | 0/180 [00:00<?, ?it/s]

[Epoch 14/30] Train Loss: 0.0484 Val Loss: 0.0776 Train Acc: 0.9861 Val Acc: 0.9583


 47%|████▋     | 84/180 [00:05<00:06, 15.45it/s]
Traceback (most recent call last):
  File "/mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/train.py", line 192, in <module>
    trainer()
  File "/mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/train.py", line 140, in trainer
    train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion)
  File "/mnt/c/Users/beeha/VSCode/! - Self-study/All HUGE Projects/Computer Vision/hutech_mushroom/src/train.py", line 40, in train_one_epoch
    running_loss += loss.item() * images.size(0)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/wandb/sdk/lib/sock_client

In [27]:
!wandb agent --count 20 {sweep_id}

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/wandb/sdk/lib/service_connection.py", line 56, in _try_connect_to_existing_service
    client.connect(token.port)
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch37/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/pytorch37/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
  